- name: Install bridge-utils network bridge utilities
  ansible.builtin.apt:
    pkg: bridge-utils
  become: true

- name: Install dnsmasq DNS forwarder
  ansible.builtin.apt:
    pkg: dnsmasq
  become: true

- name: Install wireless-tools wireless configuration utilities
  ansible.builtin.apt:
    pkg: wireless-tools
  become: true

- name: Install linssid wireless network scanner
  ansible.builtin.apt:
    pkg: linssid
  become: true

- name: Install avahi-daemon mDNS service
  ansible.builtin.apt:
    pkg: avahi-daemon
  become: true

- name: Install whois domain lookup tool
  ansible.builtin.apt:
    name: whois
  become: true
