- name: Install taskwarrior task management tool
  ansible.builtin.apt:
    name: taskwarrior
  become: true

- name: Install vit taskwarrior terminal interface
  ansible.builtin.apt:
    name: vit
  become: true
