- name: Install tor anonymizing network
  ansible.builtin.apt:
    pkg: tor
  become: true

- name: Disable tor daemon auto-start
  ansible.builtin.command: update-rc.d tor disable
  become: true
  changed_when: true

- name: Install nmap network scanner
  ansible.builtin.apt:
    pkg: nmap
  become: true

- name: Install dnsrecon DNS enumeration tool
  ansible.builtin.apt:
    pkg: dnsrecon
  become: true
