- name: Install ansible
  pip: name=ansible version=2.4.3.0 executable=pip3
  become: yes

- name: Install pywinrm for ansible windows provisioning
  pip: name=pywinrm version=0.3.0 executable=pip3
  become: yes

- name: Add VirtualBox repository key
  apt_key: url=https://www.virtualbox.org/download/{{ item }}.asc
  with_items:
  - oracle_vbox_2016
  become: yes

- name: Add VirtualBox repository
  apt_repository: repo='deb https://download.virtualbox.org/virtualbox/debian stretch contrib non-free' update_cache=yes
  become: yes

- name: Install Dynamic Kernel Module Support
  apt: pkg={{ item }}
  with_items:
  - linux-headers-{{ ansible_kernel }}
  - dkms
  become: yes

- name: Install VirtualBox
  apt: pkg=virtualbox-5.2
  become: yes

- name: Download vagrant .deb
  get_url: url=https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb dest=~/Installs/vagrant_2.1.2_x86_64.deb checksum=sha256:f614a60b258a856322f23d33a24201d26ab2555d047814fec403e834eb7d62b4
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install vagrant
  apt: deb=/tmp/Installs/vagrant_2.1.2_x86_64.deb
  become: yes

- name: Download Terraform installation resource
  get_url: url=https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip dest=~/Installs/terraform_0.11.3_linux_amd64.zip checksum=sha256:6b8a7b83954597d36bbed23913dd51bc253906c612a070a21db373eab71b277b
  register: terraform_get_url_result
  until: terraform_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Unarchive Terraform
  unarchive: src=~/Installs/terraform_0.11.3_linux_amd64.zip remote_src=yes dest=/tmp

- name: Install Terraform
  copy: src=/tmp/terraform dest=/usr/local/bin remote_src=yes mode=0755
  become: yes

- name: Get Packer installer
  get_url: url=https://releases.hashicorp.com/packer/1.2.0/packer_1.2.0_linux_amd64.zip dest=~/Installs/packer_1.2.0_linux_amd64.zip checksum=sha256:d1b0fcc4e66dfe4919c25752d028a4e4466921bf0e3f75be3bbf1c85082e8040
  register: packer_get_url_result
  until: packer_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Unarchive Packer
  unarchive: src=~/Installs/packer_1.2.0_linux_amd64.zip remote_src=yes dest=/tmp

- name: Install packer
  copy: src=/tmp/packer dest=/usr/local/bin remote_src=yes mode=0755
  become: yes

- name: Install awscli
  pip: name=awscli executable=pip3
  become: yes

- name: Install vim plugins
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
    - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
    - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}
