- name: Install cloc code metrics tool
  ansible.builtin.apt:
    name: cloc
  become: true

- name: Install curl HTTP client
  ansible.builtin.apt:
    name: curl
  become: true


- name: Install httpie HTTP client
  ansible.builtin.apt:
    name: httpie
  become: true

- name: Install icdiff side-by-side diff tool
  ansible.builtin.apt:
    name: icdiff
  become: true

- name: Install expect shell automation tool
  ansible.builtin.apt:
    name: expect
  become: true

- name: Install bc command-line calculator
  ansible.builtin.apt:
    name: bc
  become: true

- name: Install jq JSON processor
  ansible.builtin.apt:
    name: jq
  become: true

- name: Configure pbcopy and pbpaste aliases
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - alias pbcopy='xclip -selection clipboard'
    - alias pbpaste='xclip -selection clipboard -o'


- name: Install plantuml diagramming tool
  ansible.builtin.apt:
    name: plantuml
  become: true

- name: Install act GitHub Actions testing tool
  ansible.builtin.command: /usr/local/go/bin/go install github.com/nektos/act@v0.2.26
  changed_when: true
